spring.ai.ollama.base-url: http://localhost:11434
## spring.ai.ollama.chat.model: deepseek-r1:1.5b
spring.ai.ollama.chat.model: llama3.2              
spring.ai.ollama.chat.temperature: 0.7
spring.ai.ollama.chat.num-ctx: 4096
server.servlet.context-path=/api/v1
## chatbot defaults
chatbot.default.identity=Your name is Souvik. You are a helpful assistant.